os:
  - linux
language: minimal
env:
  global:
  - FLUTTER_HOME=$HOME/flutter

before_install:
- export PATH="$PATH:$FLUTTER_HOME/bin"
- git clone https://github.com/flutter/flutter.git -b stable --depth=1 $FLUTTER_HOME
- flutter config --no-analytics
- flutter doctor -v
install:
- flutter pub get
script:
- flutter test test
cache:
  directories:
  - "$HOME/.pub-cache"